#!/usr/bin/env ruby

DOMAINS = %w{
  reddit.com forums.somethingawful.com somethingawful.com digg.com
  break.com news.ycombinator.com infoq.com bebo.com twitter.com
  facebook.com blip.com youtube.com vimeo.com delicious.com
  flickr.com friendster.com hi5.com linkedin.com livejournal.com
  meetup.com myspace.com plurk.com stickam.com stumbleupon.com
  yelp.com slashdot.org
}

require 'digest/md5'
class PlayTime

  attr_accessor :path

  def initialize(path=nil)
    @path = path || "/etc/hosts"
  end

  def separator
    @separator ||= "#==#{self.class.name}/#{Digest::MD5.hexdigest(self.class.name + path)}"
  end

  def work
    File.open(path, 'r+') do |f|
      lines = f.read
      if !lines.match /#{separator}/
        self.class.overwrite_file(f) do
          extra = DOMAINS.collect { |d| "127.0.0.2\t#{d}\twww.#{d}" }
          lines << "\n\n#{separator}\n#{extra.join("\n")}\n#{separator}"
        end
      end
    end
  end

  def play
    File.open(path, 'r+') do |f|
      lines = f.read
      if lines.match /#{separator}/
        self.class.overwrite_file(f) do
          lines.gsub /([\s\n]*#{separator}.*#{separator})/m, ""
        end
      end
    end
  end

  private

  def self.overwrite_file(file, &block)
    text = yield
    file.rewind
    file.write text
    file.truncate text.length
  end

end

p = PlayTime.new(ARGV[1] || nil)

case ARGV.first
when 'start', 'begin', 'go', 'play', 'on'
  puts "Out in to the playground, children."
  p.play
else
  puts "Bums on seats, please."
  p.work
end
